export function SolitaireGame() : void{
    let solitairePositionX = 9;
    let solitairePositionY = 2;
    let solitairePositionZ = 4;
    let solitaireRotationX = 0;
    let solitaireRotationY = 0;
    let solitaireRotationZ = 0;


    // Define all cards
    var allCards = ["ac","ad","ah","as","2c","2d","2h","2s","3c","3d","3h","3s","4c","4d","4h","4s","5c","5d","5h","6s","6c","6d","6h","6s","7c","7d","7h","7s","8c","8d","8h","8s","9c","9d","9h","9s","10c","10d","10h","10s","jc","jd","jh","js","qc","qd","qh","qs","kc","kd","kh","ks"];

    // Render all cards
    var allEntityCards = [];
    // Using loop to render all 52 cards causes a freeze up
    function loadAllCards(){
        var x = 0;

        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;

        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;

        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;

        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;

        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;

        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
        allEntityCards[allCards[x]] = new Entity();
        allEntityCards[allCards[x]].addComponent(new GLTFShape("models/cards/"+allCards[x]+".gltf"));
        allEntityCards[allCards[x]].addComponent(new Transform());
        allEntityCards[allCards[x]].getComponent(Transform).scale.set(0.2, 0.2, 0.2);
        allEntityCards[allCards[x]].getComponent(Transform).position.set(solitairePositionX, solitairePositionY, solitairePositionZ - (0.001 * (x+1)));
        allEntityCards[allCards[x]].getComponent(Transform).rotation.setEuler(solitaireRotationX, solitaireRotationY, solitaireRotationZ);
        engine.addEntity(allEntityCards[allCards[x]]);
        x++;
    }

    loadAllCards();
}

